// eslint.config.mjs
import eslint from '@eslint/js'
import { defineConfig } from 'eslint/config'
import tseslint from 'typescript-eslint'

export default defineConfig([
    // --- Base recommended configs ---
    eslint.configs.recommended,
    tseslint.configs.strict,
    tseslint.configs.stylistic,

    // --- TypeScript file overrides ---
    {
        name: 'project-ts-rules',
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],

        rules: {
            'no-warning-comments': 'warn',
            'array-callback-return': 'error',
            'no-await-in-loop': 'error',
            'no-constructor-return': 'error',
            'no-inner-declarations': 'error',
            'no-promise-executor-return': 'error',
            'no-self-compare': 'error',
            'no-template-curly-in-string': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unreachable-loop': 'error',
            'no-useless-assignment': 'error',
            'require-atomic-updates': 'error',
            'accessor-pairs': 'error',
            'block-scoped-var': 'error',
            'camelcase': 'error',
            'complexity': ['error', { max: 15 }], // 20 is default
            // 'consistent-this': ['error', 'that'],
            'curly': 'error',
            'default-case': 'error',
            'default-case-last': 'error',
            'eqeqeq': 'error',
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'error',
            'logical-assignment-operators': 'error',
            'max-depth': 'error',
            'new-cap': 'error',
            'no-bitwise': 'error',
            'no-caller': 'error',
            'no-else-return': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-multi-assign': 'error',
            'no-multi-str': 'error',
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-underscore-dangle': 'error',
            'no-unneeded-ternary': 'error',
            'no-useless-call': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'error',
            'object-shorthand': 'error',
            'operator-assignment': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
            'prefer-exponentiation-operator': 'error',
            'prefer-numeric-literals': 'error',
            'prefer-object-has-own': 'error',
            'prefer-object-spread': 'error',
            'prefer-regex-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            'radix': 'error',
            // 'sort-imports': 'warn',
            'strict': 'error',
            'symbol-description': 'error',
            'vars-on-top': 'error',
            'yoda': 'error',
            'unicode-bom': 'error',
            'no-use-before-define': 'off',
            'require-yield': 'off',
            '@typescript-eslint/no-use-before-define': [
                'error',
                {
                    functions: false,
                    classes: true,
                    variables: true,
                    allowNamedExports: false,
                    enums: true,
                    typedefs: true,
                    ignoreTypeReferences: true,
                },
            ],
            'class-methods-use-this': 'off',
            '@typescript-eslint/class-methods-use-this': 'error',
            'default-param-last': 'off',
            '@typescript-eslint/default-param-last': 'error',
            'no-array-constructor': 'off',
            '@typescript-eslint/no-array-constructor': 'error',
            'no-loop-func': 'off',
            '@typescript-eslint/no-loop-func': 'error',
            // 'no-shadow': 'off',
            // '@typescript-eslint/no-shadow': 'error',
            'no-unused-expressions': 'off',
            '@typescript-eslint/no-unused-expressions': 'error',
            'no-useless-constructor': 'off',
            '@typescript-eslint/no-useless-constructor': 'error',
            '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
            '@typescript-eslint/consistent-type-imports': 'error',
            // '@typescript-eslint/explicit-function-return-type': 'error',
            '@typescript-eslint/explicit-module-boundary-types': 'error',
            '@typescript-eslint/method-signature-style': 'error',
            '@typescript-eslint/naming-convention': 'error',
            '@typescript-eslint/no-import-type-side-effects': 'error',
            '@typescript-eslint/no-unnecessary-parameter-property-assignment':
                'error',
            '@typescript-eslint/no-useless-empty-export': 'error',
            '@typescript-eslint/prefer-enum-initializers': 'error',
            'dot-notation': 'off',
            '@typescript-eslint/dot-notation': 'error',
            'no-implied-eval': 'off',
            '@typescript-eslint/no-implied-eval': 'error',
            'prefer-promise-reject-errors': 'off',
            '@typescript-eslint/prefer-promise-reject-errors': 'error',
            'require-await': 'off',
            '@typescript-eslint/require-await': 'error',
            '@typescript-eslint/consistent-type-exports': 'error',
            '@typescript-eslint/no-unnecessary-qualifier': 'error',
            '@typescript-eslint/no-unsafe-type-assertion': 'error',
            '@typescript-eslint/promise-function-async': 'error',
            '@typescript-eslint/require-array-sort-compare': 'error',
            '@typescript-eslint/strict-boolean-expressions': 'error',
            '@typescript-eslint/switch-exhaustiveness-check': 'error',
            // disable defaults for...
            '@typescript-eslint/no-non-null-assertion': 'off',
        },
    },

    // --- Type-aware linting options ---
    {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        languageOptions: {
            parserOptions: {
                tsconfigRootDir: import.meta.dirname,
                project: 'tsconfig.eslint.json', // enables type-aware linting
            },
        },
    },

    // --- Ignore output / generated files ---
    {
        ignores: ['dist', 'docs', 'coverage', '*.d.ts', 'eslint.config.mjs'],
    },
])
